### ISSUE TITLE
aca-py mediation review

### ISSUE THREAD

**Issue by baegjae** [sktston/aries-cloudagent-python#44]
현재 node mediator를 사용하고 있음.
aca-py mediation 기능이 최근 추가됨에 따라, 해당 기능을 활용 가능한지 검토 요구

**Comment by baegjae** [comment]
https://github.com/hyperledger/aries-cloudagent-python/blob/main/Mediation.md

**Comment by baegjae** [comment]
`https://github.com/hyperledger/aries-cloudagent-python/issues/1052`

`--enable-undelivered-queue` 를 사용하면 메시지를 endpoint로 보내지 않고, `trust-ping` 을 하면 메시지를 확인 할 수 있는 것으로 보임.

아래 부분은 아직 불 분명함
- 초기에 mediator와 holder가 connection을 맺는 과정
- holder가 issuer의 invitation을 receive하는 과정에서 mediator를 지정하는 과정

**Comment by airoasis** [comment]
백재야. close 햘께.
